<?php
/**
 * SimpleQuickSearchDto
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Abletech.Arxivar.Server.WebApi.Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * SimpleQuickSearchDto Class Doc Comment
 *
 * @category Class
 * @description Class of quick search that doesn&#39;t support OR search list
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SimpleQuickSearchDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'SimpleQuickSearchDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'find' => '\Swagger\Client\Model\FindDTO',
        'search_filter_dto' => '\Swagger\Client\Model\SearchDTO',
        'select_filter_dto' => '\Swagger\Client\Model\SelectDTO'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'find' => null,
        'search_filter_dto' => null,
        'select_filter_dto' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'find' => 'find',
        'search_filter_dto' => 'searchFilterDto',
        'select_filter_dto' => 'selectFilterDto'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'find' => 'setFind',
        'search_filter_dto' => 'setSearchFilterDto',
        'select_filter_dto' => 'setSelectFilterDto'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'find' => 'getFind',
        'search_filter_dto' => 'getSearchFilterDto',
        'select_filter_dto' => 'getSelectFilterDto'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['find'] = isset($data['find']) ? $data['find'] : null;
        $this->container['search_filter_dto'] = isset($data['search_filter_dto']) ? $data['search_filter_dto'] : null;
        $this->container['select_filter_dto'] = isset($data['select_filter_dto']) ? $data['select_filter_dto'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets find
     *
     * @return \Swagger\Client\Model\FindDTO
     */
    public function getFind()
    {
        return $this->container['find'];
    }

    /**
     * Sets find
     *
     * @param \Swagger\Client\Model\FindDTO $find Find information
     *
     * @return $this
     */
    public function setFind($find)
    {
        $this->container['find'] = $find;

        return $this;
    }

    /**
     * Gets search_filter_dto
     *
     * @return \Swagger\Client\Model\SearchDTO
     */
    public function getSearchFilterDto()
    {
        return $this->container['search_filter_dto'];
    }

    /**
     * Sets search_filter_dto
     *
     * @param \Swagger\Client\Model\SearchDTO $search_filter_dto search_filter_dto
     *
     * @return $this
     */
    public function setSearchFilterDto($search_filter_dto)
    {
        $this->container['search_filter_dto'] = $search_filter_dto;

        return $this;
    }

    /**
     * Gets select_filter_dto
     *
     * @return \Swagger\Client\Model\SelectDTO
     */
    public function getSelectFilterDto()
    {
        return $this->container['select_filter_dto'];
    }

    /**
     * Sets select_filter_dto
     *
     * @param \Swagger\Client\Model\SelectDTO $select_filter_dto select_filter_dto
     *
     * @return $this
     */
    public function setSelectFilterDto($select_filter_dto)
    {
        $this->container['select_filter_dto'] = $select_filter_dto;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


