<?php
/**
 * AdditionalConcreteFieldsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Abletech.Arxivar.Server.WebApi.Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AdditionalConcreteFieldsTest Class Doc Comment
 *
 * @category    Class */
// * @description Class of Additional Fields
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AdditionalConcreteFieldsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AdditionalConcreteFields"
     */
    public function testAdditionalConcreteFields()
    {
    }

    /**
     * Test attribute "additional_fields_group"
     */
    public function testPropertyAdditionalFieldsGroup()
    {
    }

    /**
     * Test attribute "additional_fields_string"
     */
    public function testPropertyAdditionalFieldsString()
    {
    }

    /**
     * Test attribute "additional_fields_boolean"
     */
    public function testPropertyAdditionalFieldsBoolean()
    {
    }

    /**
     * Test attribute "additional_fields_classe"
     */
    public function testPropertyAdditionalFieldsClasse()
    {
    }

    /**
     * Test attribute "additional_fields_combo"
     */
    public function testPropertyAdditionalFieldsCombo()
    {
    }

    /**
     * Test attribute "additional_fields_date_time"
     */
    public function testPropertyAdditionalFieldsDateTime()
    {
    }

    /**
     * Test attribute "additional_fields_multivalue"
     */
    public function testPropertyAdditionalFieldsMultivalue()
    {
    }

    /**
     * Test attribute "additional_fields_int"
     */
    public function testPropertyAdditionalFieldsInt()
    {
    }

    /**
     * Test attribute "additional_fields_double"
     */
    public function testPropertyAdditionalFieldsDouble()
    {
    }

    /**
     * Test attribute "additional_fields_table"
     */
    public function testPropertyAdditionalFieldsTable()
    {
    }
}
