<?php
/**
 * FieldFormulaCalculateArchiveCriteriaDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Abletech.Arxivar.Server.WebApi.Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FieldFormulaCalculateArchiveCriteriaDtoTest Class Doc Comment
 *
 * @category    Class */
// * @description Class of criteria fields to calculate formula
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FieldFormulaCalculateArchiveCriteriaDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FieldFormulaCalculateArchiveCriteriaDto"
     */
    public function testFieldFormulaCalculateArchiveCriteriaDto()
    {
    }

    /**
     * Test attribute "search_filter_dto"
     */
    public function testPropertySearchFilterDto()
    {
    }

    /**
     * Test attribute "field_name"
     */
    public function testPropertyFieldName()
    {
    }

    /**
     * Test attribute "formula"
     */
    public function testPropertyFormula()
    {
    }
}
