<?php
/**
 * FolderArchiveModeInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Abletech.Arxivar.Server.WebApi.Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FolderArchiveModeInfoTest Class Doc Comment
 *
 * @category    Class */
// * @description Class of information for profiling in folder
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FolderArchiveModeInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FolderArchiveModeInfo"
     */
    public function testFolderArchiveModeInfo()
    {
    }

    /**
     * Test attribute "folder_id"
     */
    public function testPropertyFolderId()
    {
    }

    /**
     * Test attribute "folder_name"
     */
    public function testPropertyFolderName()
    {
    }

    /**
     * Test attribute "rules"
     */
    public function testPropertyRules()
    {
    }

    /**
     * Test attribute "archive_mode"
     */
    public function testPropertyArchiveMode()
    {
    }
}
