<?php
/**
 * LogDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Abletech.Arxivar.Server.WebApi.Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LogDTOTest Class Doc Comment
 *
 * @category    Class */
// * @description Class of log item
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LogDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LogDTO"
     */
    public function testLogDTO()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "log_level"
     */
    public function testPropertyLogLevel()
    {
    }

    /**
     * Test attribute "log_message"
     */
    public function testPropertyLogMessage()
    {
    }

    /**
     * Test attribute "log_date"
     */
    public function testPropertyLogDate()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "user_name_complete"
     */
    public function testPropertyUserNameComplete()
    {
    }

    /**
     * Test attribute "ip_logger"
     */
    public function testPropertyIpLogger()
    {
    }

    /**
     * Test attribute "info_type"
     */
    public function testPropertyInfoType()
    {
    }

    /**
     * Test attribute "info_type_message"
     */
    public function testPropertyInfoTypeMessage()
    {
    }

    /**
     * Test attribute "info_int"
     */
    public function testPropertyInfoInt()
    {
    }

    /**
     * Test attribute "session_id"
     */
    public function testPropertySessionId()
    {
    }

    /**
     * Test attribute "software_name"
     */
    public function testPropertySoftwareName()
    {
    }

    /**
     * Test attribute "software_type"
     */
    public function testPropertySoftwareType()
    {
    }

    /**
     * Test attribute "info_string"
     */
    public function testPropertyInfoString()
    {
    }

    /**
     * Test attribute "parent_id"
     */
    public function testPropertyParentId()
    {
    }

    /**
     * Test attribute "log_kind"
     */
    public function testPropertyLogKind()
    {
    }

    /**
     * Test attribute "history_int"
     */
    public function testPropertyHistoryInt()
    {
    }

    /**
     * Test attribute "history_string"
     */
    public function testPropertyHistoryString()
    {
    }

    /**
     * Test attribute "childs"
     */
    public function testPropertyChilds()
    {
    }
}
