<?php
/**
 * MaskDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Abletech.Arxivar.Server.WebApi.Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MaskDTOTest Class Doc Comment
 *
 * @category    Class */
// * @description Class of mask to archive documents
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MaskDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MaskDTO"
     */
    public function testMaskDTO()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "mask_name"
     */
    public function testPropertyMaskName()
    {
    }

    /**
     * Test attribute "mask_description"
     */
    public function testPropertyMaskDescription()
    {
    }

    /**
     * Test attribute "predefined_profile_id"
     */
    public function testPropertyPredefinedProfileId()
    {
    }

    /**
     * Test attribute "user"
     */
    public function testPropertyUser()
    {
    }

    /**
     * Test attribute "external_id"
     */
    public function testPropertyExternalId()
    {
    }

    /**
     * Test attribute "is_root"
     */
    public function testPropertyIsRoot()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "pa_mode"
     */
    public function testPropertyPaMode()
    {
    }

    /**
     * Test attribute "show_additional"
     */
    public function testPropertyShowAdditional()
    {
    }

    /**
     * Test attribute "kind"
     */
    public function testPropertyKind()
    {
    }

    /**
     * Test attribute "show_groups"
     */
    public function testPropertyShowGroups()
    {
    }

    /**
     * Test attribute "user_complete_name"
     */
    public function testPropertyUserCompleteName()
    {
    }

    /**
     * Test attribute "predefined_profile"
     */
    public function testPropertyPredefinedProfile()
    {
    }

    /**
     * Test attribute "mask_details"
     */
    public function testPropertyMaskDetails()
    {
    }

    /**
     * Test attribute "mask_class_options"
     */
    public function testPropertyMaskClassOptions()
    {
    }
}
