<?php
/**
 * SearchConcreteDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Abletech.Arxivar.Server.WebApi.Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SearchConcreteDTOTest Class Doc Comment
 *
 * @category    Class */
// * @description Class of search
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SearchConcreteDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SearchConcreteDTO"
     */
    public function testSearchConcreteDTO()
    {
    }

    /**
     * Test attribute "da_a_and_or"
     */
    public function testPropertyDaAAndOr()
    {
    }

    /**
     * Test attribute "contact_fields"
     */
    public function testPropertyContactFields()
    {
    }

    /**
     * Test attribute "aoo_field"
     */
    public function testPropertyAooField()
    {
    }

    /**
     * Test attribute "document_type_field"
     */
    public function testPropertyDocumentTypeField()
    {
    }

    /**
     * Test attribute "protocol_field"
     */
    public function testPropertyProtocolField()
    {
    }

    /**
     * Test attribute "conservation_field"
     */
    public function testPropertyConservationField()
    {
    }

    /**
     * Test attribute "stamp_field"
     */
    public function testPropertyStampField()
    {
    }

    /**
     * Test attribute "date_time_fields"
     */
    public function testPropertyDateTimeFields()
    {
    }

    /**
     * Test attribute "string_fields"
     */
    public function testPropertyStringFields()
    {
    }

    /**
     * Test attribute "int_fields"
     */
    public function testPropertyIntFields()
    {
    }

    /**
     * Test attribute "bool_fields"
     */
    public function testPropertyBoolFields()
    {
    }

    /**
     * Test attribute "double_fields"
     */
    public function testPropertyDoubleFields()
    {
    }

    /**
     * Test attribute "string_list_fields"
     */
    public function testPropertyStringListFields()
    {
    }

    /**
     * Test attribute "group_fields"
     */
    public function testPropertyGroupFields()
    {
    }
}
