<?php
/**
 * SharingHtmlDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Abletech.Arxivar.Server.WebApi.Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SharingHtmlDTOTest Class Doc Comment
 *
 * @category    Class */
// * @description SharingHtmlDTO
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SharingHtmlDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SharingHtmlDTO"
     */
    public function testSharingHtmlDTO()
    {
    }

    /**
     * Test attribute "html_kind"
     */
    public function testPropertyHtmlKind()
    {
    }

    /**
     * Test attribute "header"
     */
    public function testPropertyHeader()
    {
    }

    /**
     * Test attribute "body_header"
     */
    public function testPropertyBodyHeader()
    {
    }

    /**
     * Test attribute "body_content"
     */
    public function testPropertyBodyContent()
    {
    }

    /**
     * Test attribute "body_footer"
     */
    public function testPropertyBodyFooter()
    {
    }

    /**
     * Test attribute "footer"
     */
    public function testPropertyFooter()
    {
    }

    /**
     * Test attribute "lang"
     */
    public function testPropertyLang()
    {
    }
}
