<?php
/**
 * LayoutApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Abletech.Arxivar.Server.WebApi.Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * LayoutApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LayoutApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for layoutDelete
     *
     * This call delete an existent layout.
     *
     */
    public function testLayoutDelete()
    {
    }

    /**
     * Test case for layoutGetById
     *
     * This call returns the single layout by the given id.
     *
     */
    public function testLayoutGetById()
    {
    }

    /**
     * Test case for layoutGetByTask
     *
     * This call returns the layout for the given user, the given type and the given utilization.
     *
     */
    public function testLayoutGetByTask()
    {
    }

    /**
     * Test case for layoutGetByType
     *
     * This call returns all layout of the specified type.
     *
     */
    public function testLayoutGetByType()
    {
    }

    /**
     * Test case for layoutGetByUser
     *
     * This call returns the layout for the given user, the given type and the given utilization.
     *
     */
    public function testLayoutGetByUser()
    {
    }

    /**
     * Test case for layoutPost
     *
     * This call save a new layout.
     *
     */
    public function testLayoutPost()
    {
    }

    /**
     * Test case for layoutPut
     *
     * This call update a layout.
     *
     */
    public function testLayoutPut()
    {
    }

    /**
     * Test case for layoutPutChangeOrder
     *
     * This call changes the layout order for a given layout.
     *
     */
    public function testLayoutPutChangeOrder()
    {
    }
}
