<?php
/**
 * QuickSearchesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Abletech.Arxivar.Server.WebApi.Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * QuickSearchesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class QuickSearchesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for quickSearchesChangeShowFields
     *
     * This call changes the flag that enable show of the search fields.
     *
     */
    public function testQuickSearchesChangeShowFields()
    {
    }

    /**
     * Test case for quickSearchesDeleteQuickSearchById
     *
     * This call deletes a quick search.
     *
     */
    public function testQuickSearchesDeleteQuickSearchById()
    {
    }

    /**
     * Test case for quickSearchesGetQuickSearch
     *
     * This call returns all quick search.
     *
     */
    public function testQuickSearchesGetQuickSearch()
    {
    }

    /**
     * Test case for quickSearchesGetQuickSearchById
     *
     * Thi call returns a quick search by its id.
     *
     */
    public function testQuickSearchesGetQuickSearchById()
    {
    }

    /**
     * Test case for quickSearchesPost
     *
     * This call adds a new quinck search.
     *
     */
    public function testQuickSearchesPost()
    {
    }

    /**
     * Test case for quickSearchesPut
     *
     * This call updates a quick search.
     *
     */
    public function testQuickSearchesPut()
    {
    }

    /**
     * Test case for quickSearchesRename
     *
     * This call renames a quick search.
     *
     */
    public function testQuickSearchesRename()
    {
    }
}
