<?php
/**
 * TaskWorkNotesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Abletech.Arxivar.Server.WebApi.Services
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * TaskWorkNotesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TaskWorkNotesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for taskWorkNotesDeleteNote
     *
     * This call deletes a process note.
     *
     */
    public function testTaskWorkNotesDeleteNote()
    {
    }

    /**
     * Test case for taskWorkNotesGetByProcessId
     *
     * This call returns all notes in a process.
     *
     */
    public function testTaskWorkNotesGetByProcessId()
    {
    }

    /**
     * Test case for taskWorkNotesInsertNewNote
     *
     * This call adds a new note to a process.
     *
     */
    public function testTaskWorkNotesInsertNewNote()
    {
    }

    /**
     * Test case for taskWorkNotesUpdateNote
     *
     * This call updates a process note.
     *
     */
    public function testTaskWorkNotesUpdateNote()
    {
    }
}
